// See https://aka.ms/new-console-template for more information

using GhibliUniverse.Console;
using GhibliUniverse.Console.DataPersistence;
using GhibliUniverse.Core.Domain.Models;
using GhibliUniverse.Core.Services;

var filmUniverse = new FilmUniverse();
var filmService = new FilmService();
var voiceActorService = new VoiceActorService();
var reviewService = new ReviewService(filmService);
var commandLine = new CommandLine();
var argumentProcessor = new ArgumentProcessor(commandLine, filmUniverse);
var fileOperations = new FileOperations();
var filmPersistence = new FilmPersistence(filmService, fileOperations);
var voiceActorPersistence = new VoiceActorPersistence(voiceActorService, fileOperations);
var reviewPersistence = new ReviewPersistence(filmService, reviewService, fileOperations);
var filmVoiceActorPersistence = new FilmVoiceActorPersistence(filmService, voiceActorService, fileOperations);
filmPersistence.ReadingStep();
// filmService.PopulateFilmsList(1);
// voiceActorService.PopulateVoiceActorsList(1);
// reviewService.CreateReview(Guid.Parse("00000000-0000-0000-0000-000000000000"), 10);
// voiceActorService.DeleteVoiceActor(Guid.Parse("c320db9c-cc9f-403f-a84b-1c1d36287d88"));
// filmService.DeleteFilm(Guid.Parse("00000000-0000-0000-0000-000000000000"));
// filmService.DeleteFilm(Guid.Parse("11111111-1111-1111-1111-111111111111"));
voiceActorPersistence.ReadingStep();
reviewPersistence.ReadingStep();
// var mov = filmService.GetAllFilms();
// mov[0].VoiceActors.Add(voiceActorService.GetAllVoiceActors()[0]);
filmVoiceActorPersistence.ReadingStep();
// argumentProcessor.Process();
// filmUniverse.PopulateFilmsList(2);
// filmUniverse.CreateFilm("Batman Begins", "A man dresses up as; a bat, and fights crime, his name is, vengeance.", "Christopher Nolan", "Hans Zimmer", 1999);
// // filmUniverse.CreateVoiceActor("Henry", "Dot");
// filmUniverse.DeleteFilmRating(new Guid("00000000-0000-0000-0000-000000000000"), new Guid("62b20cb0-ae09-4156-a831-06065aa44e78"));
// filmUniverse.DeleteVoiceActor(new Guid("aeca3ca7-d5e2-43ac-ab91-77bf529000dc"));
// filmUniverse.DeleteVoiceActor(new Guid("c2f6fcbb-71e2-4379-b817-a4cb3582ea51"));
// filmUniverse.DeleteFilmRating(new Guid("00000000-0000-0000-0000-000000000000"), new Guid("1ddac2db-cb70-4fd8-b002-5dc21a96bbd5"));
filmPersistence.WritingStep();
voiceActorPersistence.WritingStep();
reviewPersistence.WritingStep();
filmVoiceActorPersistence.WritingStep();
// var s = filmUniverse.BuildFilmList();
// Console.WriteLine(s);
var g = filmService.BuildFilmList();
Console.WriteLine(g);
var y = voiceActorService.BuildVoiceActorList();
Console.WriteLine(y);
var x = reviewService.BuildReviewList();
Console.WriteLine(x);