version: "3.8"

services:
  postgres-db:
    image: postgres
    container_name: postgres
    volumes:
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ghibliuniverse-db
      DOCKER_COMPOSE: "true"
    user: postgres
    ports:
      - "5433:5432"        

  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: ghibliuniverse-db
      DB_USER: dev
      DB_PASSWORD: password
#      SWAGGER_HOST: localhost:3000
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      DOCKER_COMPOSE: "true"
    depends_on:
      - postgres-db